rate:     1000

# planner
rng_infl:   3
threshold:  0.2
ka:         0.5
k_rep:      10
k_psi:      0.5
pl_kf_d:    10

# outerloop parameters
ol_xi:    0.707
ol_wn:    2

# eta_reference parameters
er_kf_d:  3
er_kf_dd: 3

# innerloop parameters
il_v:     25
il_xi:    0.707
il_wn:    3

# wrench estimator
we_k0:    3